version: '3'

services:
  backend:
    env_file:
        "./backend/.env"
    build: ./backend
    image: "backend-img"
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend/front
    image: "frontend-img"
    ports:
      - "3000:3000"
    links:
      - "backend:be"